server:
  error.whitelabel.enabled: false
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
      javax:
        persistence:
          query.timeout: 10000
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dota
    username: sa
    password: password
  banner:
    image:
      location: classpath:banner.png
      width: 100
      height: 15
      margin: 1
  h2:
    console:
      enabled: true
      path: /h2

logging.config: classpath:logback-${ENV:development}.xml

#Pattern Strings
pattern.killed.2: (.*)\](.*)npc_(.*)is(.*)killed(.*)by(.*)npc_dota_(.*)
pattern.killed.1: (.*)\](.*)npc_(.*)is(.*)killed(.*)by(.*)_(.*)
pattern.item: (.*)\](.*)npc_dota_hero_(.*)buys(.*)item(.*)item_(.*)
pattern.casts: (.*)\](.*)npc_dota_hero_(.*)casts(.*)ability(.*)abyssal_underlord_(.*)lvl(.*)on(.*)dota_(.*)
pattern.hit.1: (.*)\](.*)npc_dota_hero_(.*)hits(.*)npc_dota_hero_(.*)with(.*)_(.*)for(.*)damage(.*)->(.*)
pattern.hit.2: (.*)\](.*)npc_dota_hero_(.*)hits(.*)npc_dota_hero_(.*)with(.*)_(.*)for(.*)damage(.*)
